### ISSUE TITLE
gzip_nxfht_test - tests failed with nx accelerators count as ZERO due to this tests failed

### ISSUE THREAD

**Issue by kalshett** [libnxz/power-gzip#105]
P10 PowerVM:

##5gb file
[root@ltcden13-lp2 samples]# dd if=/dev/urandom of=5gb-file bs=1073741824 count=150
dd: warning: partial read (33554431 bytes); suggest iflag=fullblock
0+150 records in
0+150 records out
5033164650 bytes (5.0 GB, 4.7 GiB) copied, 20.2119 s, 249 MB/s

#create sample 1M file from 5gb
[root@ltcden13-lp2 samples]# head -c 1M 5gb-file > head.5gb-file.1M

[root@ltcden13-lp2 samples]# ls -l head.5gb-file.1M 
-rw-r--r--. 1 root root 1048576 Nov 15 03:27 head.5gb-file.1M

#run fixed compress type - "nxfht" tests
[root@ltcden13-lp2 samples]# ./gzip_nxfht_test head.5gb-file.1M
crb 0x1b3f2800
file head.5gb-file.1M read, 1048576 bytes
compressed 1048576 to 1105902 bytes total, crc32=ec354225

[root@ltcden13-lp2 samples]# cat /tmp/nx.log 
[2021/11/15 03:27:49] pid 82329: nx_zlib.c:1009: Error: NX-gzip accelerators found: 0

**Comment by kalshett** [comment]
For time being Haren pointed put that an issue with below code - nx_zlib.c
>>>>
        nx_count = nx_enumerate_engines();
        nx_dev_count = nx_count;
        if (nx_count == 0) {
                prt_err("NX-gzip accelerators found: %d\n", nx_count);
                return;
        }
>>>

So for test to continue we have made, nx_count as non-zero and continued, however this needs to be fixed.
nx_dev_count = nx_count = 2;

**Comment by tuliom** [comment]
@kalshett which commit ID was used in this test?

**Comment by kalshett** [comment]
I git clone master copy.
https://github.com/libnxz/power-gzip

**Comment by tuliom** [comment]
@kalshett The support for PowerVM and Power10 is still under development in the `develop` branch.
In this project, we leave the `master` branch only for stable releases.

Could you try again with the `develop` branch and see if this works for you?
I remember we had already fixed this issue there.

**Comment by kalshett** [comment]
Yes, with develop branch it works fine.

**Comment by tuliom** [comment]
Thanks!

Then I'm closing this issue.
