### ISSUE TITLE
oct: Regression on gzip tests

### ISSUE THREAD

**Issue by tuliom** [libnxz/power-gzip#161]
I started seeing some gzip-related failures when running oct tests recently. I can reproduce these failures without testing with large files.

After bisecting, commit 764fe41e9a232d9b724bd1760b3b941c9cdc2387 seems to be the culprit.

**Comment by rzinsly** [comment]
Can you reproduce it with 1e335c4? Seems the lack of `gzread` on 764fe41 cause other failures.
