### ISSUE TITLE
Headers are exposing internal structures, functions and macros

### ISSUE THREAD

**Issue by tuliom** [libnxz/power-gzip#17]
Ideally, libnxz would install headers that export only global functions and structures that are part of the ABI.
However, the current implementation makes it unclear to users and downstream what should really be exported.

This is particularly more complicated because the project does not provide a `make install` target yet (PR #11 ).

**Comment by pedromfcarvalho** [comment]
There also seem to be certain global functions that have no declaration in the header, e.g. nx_adler32_z. Some of them are only accessible through the zlib wrappers, and not with the standalone library.
