### ISSUE TITLE
 test_window_suspend nx_gzip test is failing with error "not available to allocate window"

### ISSUE THREAD

**Issue by Pavithra1602** [libnxz/power-gzip#184]
logs:
--------

1. git clone https://github.com/libnxz/power-gzip.git
2. cd power-gzip
3. git checkout develop
4. ./configure
5. make check

---Logs----

[  645.068770] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.193787] vas: Credits are not available to allocate window
[  645.193792] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.225060] vas: Credits are not available to allocate window
[  645.225066] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.287585] vas: Credits are not available to allocate window
[  645.287589] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.412604] vas: Credits are not available to allocate window
[  645.412608] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.443874] vas: Credits are not available to allocate window
[  645.443878] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.506393] vas: Credits are not available to allocate window
[  645.506397] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.631412] vas: Credits are not available to allocate window
[  645.631418] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.662685] vas: Credits are not available to allocate window
[  645.662689] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.725203] vas: Credits are not available to allocate window
[  645.725208] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.850222] vas: Credits are not available to allocate window
[  645.850227] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.881491] vas: Credits are not available to allocate window
[  645.881495] coproc_ioc_tx_win_open() VAS window open failed, -22
[  645.944011] vas: Credits are not available to allocate window
[  645.944017] coproc_ioc_tx_win_open() VAS window open failed, -22
FAIL: test_window_suspend
============================================================================
Testsuite summary for libnxz 0.63
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See test/serial-tests/test-suite.log
Please report to https://github.com/libnxz/power-gzip
============================================================================
make[4]: *** [Makefile:792: test-suite.log] Error 1
make[4]: Leaving directory '/root/power-gzip/test/serial-tests'
make[3]: *** [Makefile:900: check-TESTS] Error 2
make[3]: Leaving directory '/root/power-gzip/test/serial-tests'
make[2]: *** [Makefile:981: check-am] Error 2
make[2]: Leaving directory '/root/power-gzip/test/serial-tests'
make[1]: *** [Makefile:903: check-recursive] Error 1
make[1]: Leaving directory '/root/power-gzip/test'
make: *** [Makefile:536: check-recursive] Error 1
[[reply](https://bugzilla.linux.ibm.com/show_bug.cgi?id=198551#add_comment)] [[−]](https://bugzilla.linux.ibm.com/show_bug.cgi?id=198551#) Internal Only[Comment 1](https://bugzilla.linux.ibm.com/show_bug.cgi?id=198551#c1)

Bugzilla id: https://bugzilla.linux.ibm.com/show_bug.cgi?id=198551

**Comment by mscastanho** [comment]
@Pavithra1602 Note these error messages in the kernel logs are not necessarily. The kernels emits those when we try to open a window and there are no credits left. In that case libnxz is smart enough to fallback to software, which is what this test is checking.

The the test failing is indeed an issue. I've been running the test in a loop for ~1 hour now and wasn't able to reproduce it. Is it possible there were other processes accessing NX Gzip on that system at the same time this test was executing?

**Comment by Pavithra1602** [comment]
> But the test failing is indeed an issue. I've been running the test in a loop for ~1 hour now and wasn't able to reproduce it. Is it possible there were other processes accessing NX Gzip on that system at the same time this test was executing?

@mscastanho no only single test was running on the lpar. My lpar is in dedicated mode with 20 cores.

[root@ltcever59-lp6 serial-tests]# ./test_window_suspend
Credits before:  total: 400  used: 0
starting 399 processes
Credits after proc creation:  total: 400  used: 399
Validating CPU DLPAR capability...yes.
Validating CPU DLPAR capability...yes.
CPU 153
Credits after DLPAR:  total: 380  used: 399
Processes with suspended windows: 3774 3772
[   87.250119] vas: Credits are not available to allocate window
[   87.250136] coproc_ioc_tx_win_open() VAS window open failed, -22
ioctl() n -1, error Invalid argument
 open_device_nodes failed
[   87.253956] vas: Credits are not available to allocate window
[   87.253968] coproc_ioc_tx_win_open() VAS window open failed, -22
ioctl() n -1, error Invalid argument
 open_device_nodes failed
[   87.254700] vas: Credits are not available to allocate window


[root@ltcever59-lp6 serial-tests]# lparstat 

System Configuration
type=Dedicated mode=Capped smt=8 lcpu=19 mem=41617472 kB cpus=0 ent=20.00 

%user  %sys %wait    %idle    physc %entc lbusy   app  vcsw phint
----- ----- -----    -----    ----- ----- ----- ----- ----- -----
 0.04  0.02  0.02    99.92     0.00  0.00  0.06  0.00 253835     0

**Comment by tuliom** [comment]
```
Credits after proc creation: total: 400 used: 399
...
Credits after DLPAR: total: 380 used: 399
```
That's 20 credits less. It doesn't match with what the test was expecting (-397)...

**Comment by mscastanho** [comment]
> type=Dedicated
The test was originally tested on an LPAR with processors in Shared mode, while this one is in Dedicated mode. So maybe the actual amount of credits removed during the test is different in this case. I'll check that.

**Comment by tuliom** [comment]
I've just received a confirmation from @Pavithra1602 this issue has been fixed.
Thanks!
