### ISSUE TITLE
Getting "./gzip_nxfht_test: No such file or directory" error while running rundecomp.sh also runnumamany.sh is not available

### ISSUE THREAD

**Issue by Pavithra1602** [libnxz/power-gzip#197]
[root@ltcever87-lp3 samples]# sh ./rundecomp.sh 5gb-file
5gb-file
/usr/bin/time: cannot run ./gzip_nxfht_test: No such file or directory
Command exited with non-zero status 127
	0.00 real 	0.00 user 	0.00 sys

cat: head.5gb-file.512.nx.gz: No such file or directory
head.5gb-file.512.nx.gz: No such file or directory
Command exited with non-zero status 255
	0.03 real 	0.01 user 	0.00 sys

/usr/bin/time: cannot run ./gzip_nxfht_test: No such file or directory
Command exited with non-zero status 127
	0.00 real 	0.00 user 	0.00 sys

cat: head.5gb-file.1K.nx.gz: No such file or directory
head.5gb-file.1K.nx.gz: No such file or directory
Command exited with non-zero status 255
	0.03 real 	0.01 user 	0.00 sys

[root@ltcever87-lp3 samples]# ls
5gb-file	 gunzip_nx.o	 Makefile.am	      run-series.plot
alice29.txt	 gunzip_nx_test  Makefile.in	      run-series.sh
bad_irq_check	 gunz-numa.plot  nx_gzip	      runtests2.sh
bad_irq_check.c  gunz.plot	 nx_gzip.c	      runtests3.sh
bad_irq_check.o  gzip-series.sh  nx_gzip.o	      runtests.sh
bench_initend	 gzm		 nxlite.c	      samples_utils.c
bench_initend.c  gzm-autohdr.c	 page_faults.txt      samples_utils.h
bench_initend.o  gzm.c		 rand_pfault_check    samples_utils.o
compdecomp.c	 gzm.o		 rand_pfault_check.c  simpleapi
compdecomp_th	 gz.plot	 rand_pfault_check.o  zlib-run-series.sh
compdecomp_th.c  icswx.h	 rundecomp.sh	      zpipe
compdecomp_th.o  junk2		 rungz.sh	      zpipe.c
crc_perf_test.c  log_2nx.log	 runmany.sh	      zpipe.o
gryphon.txt	 makedata.c	 runnuma.sh
gunzip_nx.c	 Makefile	 run-series_2nx.sh
[root@ltcever87-lp3 samples]# ls gzip_nxfht_test
ls: cannot access 'gzip_nxfht_test': No such file or directory
[root@ltcever87-lp3 samples]# ./runnumamany.sh 5gb-file
-bash: ./runnumamany.sh: No such file or directory
[root@ltcever87-lp3 samples]# find / -iname runnumamany.sh
[root@ltcever87-lp3 samples]

**Comment by tuliom** [comment]
These files have been removed because they aren't needed anymore and were confusing users.
See the commit message from: https://github.com/libnxz/power-gzip/commit/5ceecbbd888cc195e2e18511b704cb6ced33a3e6
