### ISSUE TITLE
Review the usage of crc32_ppc and nx_crc32

### ISSUE THREAD

**Issue by tuliom** [libnxz/power-gzip#29]
`crc32_ppc` provides a vectorized implementation, while `nx_crc32` is more generic.
libnxz needs a CRC32 implementation internally to create header checksum, which is just "a few bytes".
Vectorized code are rarely the fastest implementation for small length.

Can we use the vectorized code in all scenarios even if it isn't the fastest for small length? i.e. the impact would be small.
If not, we may need to implement a smart switch depending on the length.

**Comment by tuliom** [comment]
@abalib just sent me the following regarding the usage of vectorized code for all scenarios:
> I think the answer is yes.   We should test it though.  I can't remember now if there are any gotchas

**Comment by abalib** [comment]
Your idea of using only the vectorized code makes sense to me.  In my 
humble opinion, no need for a smart switch.  This library only runs on 
POWER anyway.

Although, I can't remember now if there are any gotchas with small data. 
Testing should reveal if any.
