### ISSUE TITLE
Stop opening VAS window for each inflate/deflate call

### ISSUE THREAD

**Issue by tuliom** [libnxz/power-gzip#30]
In commit https://github.com/libnxz/power-gzip/commit/32dabcb5b25cf86f77ed701fcf11024b3073448f , the default value for `disable_saved_nx_devp` was modified and a VAS window was opened for each inflate/deflate call.

This is more expensive because (quoting Haren Mynemi) it requires to open/close windows, but also setup and freeup IRQ mapping.

**Comment by mscastanho** [comment]
Fixed by #107
