### ISSUE TITLE
is planned an AIX version ?

### ISSUE THREAD

**Issue by openmax** [libnxz/power-gzip#73]
like the subject ...

on Power run linux , aix and IBMi ..

**Comment by abalib** [comment]
https://www.ibm.com/support/pages/using-power9%E2%84%A2-nx-gzip-accelerator-aix

**Comment by abalib** [comment]
https://community.ibm.com/community/user/power/blogs/brian-veale1/2020/11/09/power9-gzip-data-acceleration-with-ibm-aix?CommunityKey=daa942cb-b783-4fd3-ba27-a2d7462f9530

**Comment by openmax** [comment]
ok true , but without source i can't rebuild for IBMi pase ( environment similar to AIX ) ...
thanks anyway

**Comment by abalib** [comment]
> ok true , but without source i can't rebuild for IBMi pase ( environment similar to AIX ) ...
> thanks anyway

I am checking the IBM i support for you.

**Comment by abalib** [comment]
> https://kadler.io/posts/#
> 
> example of an ibmers that port opensource aix source to IBMi PASE ...
> 
> IBMi pase is kind of AIX , with source for aix you can build on PASE with little effort ...

Hi Massimo, I was told that you have a private channel with an IBMi developer.  You may get more if you contact him directly about the issue.  This github repo does not cover AIX, IBMi or Z support.  It is specifically for power Linux support.
