### ISSUE TITLE
When compressing 0 byte file, nxgzip and gzip command have different results.

### ISSUE THREAD

**Issue by guanhj-ips** [libnxz/power-gzip#76]
When compressing 0 byte file, nxgzip result is 0 byte file. when using gzip command, the result is 29 bytes. 

[root@localhost tmp]# touch zerobyte
[root@localhost tmp]# LD_PRELOAD=./libnxz.so ./gzip_test zerobyte -c > zerobyte.nxgzip.gz
[root@localhost tmp]# gzip zerobyte -c > zerobyte.soft.gz
[root@localhost tmp]# ls -l
total 304
-rwxr-xr-x 1 root root  76712 Sep 17 17:27 gzip_test
lrwxrwxrwx 1 root root     14 Sep 17 17:28 libnxz.so -> libnxz.so.0.62
-rw-r--r-- 1 root root 227056 Sep 17 17:27 libnxz.so.0.62
-rw-r--r-- 1 root root      0 Sep 17 17:28 zerobyte
-rw-r--r-- 1 root root      0 Sep 17 17:29 zerobyte.nxgzip.gz
-rw-r--r-- 1 root root     29 Sep 17 17:29 zerobyte.soft.gz

**Comment by mscastanho** [comment]
This has been fixed by #100.
